using System;
using System.Collections.Generic;
using System.IO;
using System.Text;

namespace LocalIconStudio {
static class L {
    public static bool English;
    public static string SettingsPath=Path.Combine(Program.Data,"ui-language.txt");
    static readonly Dictionary<string,string> Strings=new Dictionary<string,string> {
        {"ChatGPT · Prüfen …","ChatGPT · Checking …"},
        {"ChatGPT · Angemeldet","ChatGPT · Signed in"},
        {"ChatGPT · Verbunden","ChatGPT · Connected"},
        {"ChatGPT · Nicht angemeldet","ChatGPT · Signed out"},
        {"ChatGPT · Login erneuern","ChatGPT · Sign in again"},
        {"ChatGPT · Abo anmelden","ChatGPT · Subscription login"},
        {"ChatGPT · Setup nötig","ChatGPT · Setup required"},
        {"ChatGPT · Status unklar","ChatGPT · Status unknown"},
        {"ChatGPT-Anmeldung vorhanden. Die Online-Verbindung wird beim Generieren geprüft.","ChatGPT sign-in is stored. The online connection is checked when generating."},
        {"ChatGPT hat die letzte Bildgenerierung erfolgreich abgeschlossen.","ChatGPT successfully completed the last image generation."},
        {"Du bist noch nicht mit ChatGPT angemeldet.","You are not signed in to ChatGPT yet."},
        {"Deine Anmeldung konnte nicht erneuert werden. Bitte melde dich erneut mit ChatGPT an.","Your sign-in could not be refreshed. Please sign in to ChatGPT again."},
        {"Es ist ein API-Zugang aktiv. Für dieses Tool bitte mit deinem ChatGPT-Abo anmelden.","An API login is active. Please sign in with your ChatGPT subscription for this tool."},
        {"Codex CLI wurde nicht gefunden. Installiere zuerst Codex, um die Bildgenerierung zu nutzen.","Codex CLI was not found. Install Codex first to use image generation."},
        {"Der Anmeldestatus konnte nicht festgestellt werden. Du kannst es über den ChatGPT-Button erneut versuchen.","The sign-in status could not be determined. Use the ChatGPT button to try again."},
        {"DEIN ZUGANG ZUR BILDGENERIERUNG","CONNECT IMAGE GENERATION"},
        {"Anbieter: ChatGPT / Codex\nMelde dich mit deinem bestehenden Abo im Browser an.\n\nOhne Login kannst du Bilder laden und als ICO speichern.\nWeitere Anbieter sind derzeit nicht angebunden.","Provider: ChatGPT / Codex\nSign in with your existing subscription in the browser.\n\nWithout signing in, you can load images and save ICO files.\nOther providers are not connected yet."},
        {"Erneut anmelden","Sign in again"},
        {"Mit ChatGPT anmelden","Sign in with ChatGPT"},
        {"Weiter","Continue"},
        {"Nur ICO-Export","ICO export only"},
        {"Generieren","Generate"},
        {"Neu generieren","Regenerate"},
        {"Abbrechen","Cancel"},
        {"Bild laden …","Load image …"},
        {"ChatGPT-Anmeldung","ChatGPT sign-in"},
        {"Text löschen","Clear text"},
        {"Meine Icons","My icons"},
        {"Meine Icons (","My icons ("},
        {"Meine Icons  /  ","My icons  /  "},
        {"GLYPHLUME · Meine Icons","GLYPHLUME · My icons"},
        {"Ein Icon anklicken, um Bild und Prompt wieder zu öffnen.","Click an icon to reopen its image and prompt."},
        {"Hier erscheinen deine fertig generierten Icons.","Your generated icons will appear here."},
        {"Galerie nach oben scrollen","Scroll gallery up"},
        {"Galerie nach unten scrollen","Scroll gallery down"},
        {"Text nach oben scrollen","Scroll text up"},
        {"Text nach unten scrollen","Scroll text down"},
        {"Deine Idee. Dein Icon.  /  Generieren, auswählen und als ICO speichern.","Your idea. Your icon.  /  Generate, choose and save as ICO."},
        {"DEIN PROMPT","YOUR PROMPT"},
        {"Prompt geleert.","Prompt cleared."},
        {"ICO-Größe inklusive kleinerer Größen.\nTransparenz bleibt erhalten.","ICO size includes smaller sizes.\nTransparency is preserved."},
        {"Bildgenerierung online · ICO-Export lokal","Image generation online · ICO export locally"},
        {"KI-Generierung: ChatGPT-Abo + Login\nBildimport & ICO-Export: ohne Login","AI generation: ChatGPT subscription + sign-in\nImage import & ICO export: no sign-in needed"},
        {"Weitere Anbieter sind derzeit nicht angebunden.","Other providers are not connected yet."},
        {"MAXIMALE ICO-GRÖSSE","MAXIMUM ICO SIZE"},
        {" · inklusive kleinerer Größen"," · includes smaller sizes"},
        {"Die gewählte Größe und alle angebotenen kleineren Größen werden gemeinsam in einer ICO-Datei gespeichert.","The selected size and all available smaller sizes are saved together in one ICO file."},
        {"Als .ico speichern …","Save as .ico …"},
        {"Verknüpfung wählen …","Choose shortcut …"},
        {"Icon anwenden","Apply icon"},
        {"Bereit. Motiv eingeben und generieren.","Ready. Describe your icon and generate."},
        {"WIRD GENERIERT …  ","GENERATING …  "},
        {"WIRD GENERIERT …","GENERATING …"},
        {"WIRD\nGENERIERT","GENERATING\nICON"},
        {"Laufenden Auftrag abbrechen und Fenster schließen?","Cancel the current task and close the window?"},
        {"Mindestens eine ICO-Größe auswählen.","Select at least one ICO size."},
        {"Eine ICO-Datei mit ","Save one ICO file with "},
        {" ausgewählten Größen speichern."," selected sizes."},
        {"Icon aus der Galerie geöffnet. Bereit zum Speichern oder Anwenden.","Icon opened from the gallery. Ready to save or apply."},
        {"Ziel: ","Target: "},
        {"Keine Verknüpfung ausgewählt.\nWähle zuerst die gewünschte .lnk-Datei.","No shortcut selected.\nChoose the .lnk file you want to update."},
        {"Es ist noch kein Ziel ausgewählt.","No target selected yet."},
        {"Icon auf diese Verknüpfung anwenden:\n","Apply the icon to this shortcut:\n"},
        {"Zuerst eine Verknüpfung auswählen.","Choose a shortcut first."},
        {"Welche Verknüpfung soll dieses Icon erhalten?","Which shortcut should receive this icon?"},
        {"Windows-Verknüpfung (*.lnk)|*.lnk","Windows shortcut (*.lnk)|*.lnk"},
        {"Ziel gewählt: ","Target selected: "},
        {". Mit „Icon anwenden“ übernehmen.",". Click “Apply icon” to confirm."},
        {"Vorgang nicht abgeschlossen. Details im Auftragsordner.","Operation incomplete. See the task folder for details."},
        {"GLYPHLUME · Hinweis","GLYPHLUME · Notice"},
        {"Schließen","Close"},
        {"Beschreibe zuerst dein Icon.","Describe your icon first."},
        {"Vorschau fertig. Speichern oder neu generieren.","Preview ready. Save or regenerate."},
        {"Auftrag abgebrochen. Die bisherige Vorschau bleibt erhalten.","Task cancelled. The previous preview is preserved."},
        {"ChatGPT-Anmeldung öffnet sich im Browser …","ChatGPT sign-in is opening in your browser …"},
        {"Anmeldung nicht abgeschlossen. Bitte erneut versuchen.","Sign-in incomplete. Please try again."},
        {"Angemeldet. Du kannst jetzt generieren.","Signed in. You can now generate."},
        {"Anmeldung abgebrochen.","Sign-in cancelled."},
        {"Bitte ein Bild bis maximal 8192 × 8192 px laden.","Please load an image no larger than 8192 × 8192 px."},
        {"Bild geladen. Bereit für den ICO-Export.","Image loaded. Ready to export as ICO."},
        {"Bilder|*.png;*.jpg;*.jpeg;*.bmp;*.ico|Alle Dateien|*.*","Images|*.png;*.jpg;*.jpeg;*.bmp;*.ico|All files|*.*"},
        {"Windows-Symbol (*.ico)|*.ico","Windows icon (*.ico)|*.ico"},
        {"Mein-Icon.ico","My-Icon.ico"},
        {"ICO gespeichert. Dateipfad in die Zwischenablage kopiert.","ICO saved. File path copied to the clipboard."},
        {"Icon auf „","Icon applied to “"},
        {"“ angewendet. Original gesichert.","”. Original backed up."},
        {"Dein Icon erscheint hier","Your icon will appear here"},
        {"Bitte mindestens eine gültige ICO-Größe auswählen.","Please select at least one valid ICO size."},
        {"ICO konnte nicht validiert werden.","The ICO could not be validated."},
        {"Bitte eine vorhandene .lnk-Verknüpfung auswählen.","Please choose an existing .lnk shortcut."},
        {"Der Prompt konnte nicht als UTF-8 gelesen werden.","The prompt could not be read as UTF-8."},
        {"Codex CLI nicht gefunden. Bitte Codex installieren.","Codex CLI not found. Please install Codex."},
        {"Zeitlimit nach 10 Minuten erreicht. Der Auftrag wurde beendet; ein neuer Versuch erfolgt nur per Klick.","The 10-minute time limit was reached. The task was stopped; click Generate to try again."},
        {"Codex hat den Auftrag beendet (Code ","Codex ended the task (code "},
        {"Codex hat kein Bild zurückgegeben. Protokoll im Ordner: ","Codex returned no image. Logs are in: "},
        {"Codex lieferte keinen Pfad aus seinem Bildausgabe-Ordner.","Codex returned a path outside its generated images folder."},
        {"Das Bild ist zu klein.","The image is too small."},
        {"Ein türkisfarbener 3D-Würfel mit abgerundeten Kanten, klares minimalistisches App-Icon, transparenter Hintergrund.","A turquoise 3D cube with rounded edges, a clean minimalist app icon, transparent background."},
        {"Sprache: DE","Language: EN"},
        {"Sprache gewechselt.","Language changed."}
    };
    public static string T(string german){string translated;return English&&Strings.TryGetValue(german,out translated)?translated:german;}
    public static string Key(string text){foreach(var pair in Strings)if(pair.Value==text)return pair.Key;return text;}
    public static void Load(){try{English=File.Exists(SettingsPath)&&File.ReadAllText(SettingsPath).Trim()=="en";}catch(IOException){}catch(UnauthorizedAccessException){}}
    public static void Set(bool english,bool persist){if(persist){Directory.CreateDirectory(Path.GetDirectoryName(SettingsPath));File.WriteAllText(SettingsPath,english?"en":"de",Encoding.UTF8);}English=english;}
}
}
